// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bvsRV3sCqTqjcx7qUmVTwVWxR7nK1LE',
    appId: '1:361354074193:web:57538ce44e3040c1674070',
    messagingSenderId: '361354074193',
    projectId: 'flutter-chat-app-2fb3a',
    authDomain: 'flutter-chat-app-2fb3a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2fb3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFTI6pOk0uzTq-VCalPbFYhxARHStEzKY',
    appId: '1:361354074193:android:ffc5e27a5f3a6d66674070',
    messagingSenderId: '361354074193',
    projectId: 'flutter-chat-app-2fb3a',
    storageBucket: 'flutter-chat-app-2fb3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEc-b9txQLygI-i8cntfc_bkx4XeUzRrA',
    appId: '1:361354074193:ios:e1420537869a9a19674070',
    messagingSenderId: '361354074193',
    projectId: 'flutter-chat-app-2fb3a',
    storageBucket: 'flutter-chat-app-2fb3a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEc-b9txQLygI-i8cntfc_bkx4XeUzRrA',
    appId: '1:361354074193:ios:e1420537869a9a19674070',
    messagingSenderId: '361354074193',
    projectId: 'flutter-chat-app-2fb3a',
    storageBucket: 'flutter-chat-app-2fb3a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bvsRV3sCqTqjcx7qUmVTwVWxR7nK1LE',
    appId: '1:361354074193:web:34aa01ce5e5caee4674070',
    messagingSenderId: '361354074193',
    projectId: 'flutter-chat-app-2fb3a',
    authDomain: 'flutter-chat-app-2fb3a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2fb3a.firebasestorage.app',
  );

}